{__NOLAYOUT__}<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>用户管理系统</title>
    <link rel="stylesheet" href="/static/zui/css/zui.min.css">
</head>
<body>
<div class="container-fluid">
    <form method="post" id="loginForm">
        <fieldset>
            <div class="form-group">
                <label>用户名:</label>
                <input type="text" class="form-control" placeholder="请输入用户名或者手机号/邮箱" name="username" id="username">
            </div>
            <div class="form-group">
                <label>密码:</label>
                <input type="password" class="form-control" placeholder="请输入密码" name="password" id="password">
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="remember" checked>记住密码
                    </label>
                </div>
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block">登录</button>
        <a href="/user/login/register/" class="btn btn-block">注册账号</a>
    </form>
</div>
</body>
</html>