{__NOLAYOUT__}<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>用户管理系统</title>
    <link rel="stylesheet" href="/static/zui/css/zui.min.css">
</head>
<body>
<div class="container-fluid">
    <form method="post" id="registerForm">
        <fieldset>
            <div class="form-group">
                <label>用户名:</label>
                <input type="text" class="form-control" placeholder="请输入用户名或者手机号/邮箱" name="username" id="username">
            </div>
            <div class="form-group">
                <label>密码:</label>
                <input type="password" class="form-control" placeholder="请输入密码" name="password" id="password">
            </div>
            <div class="form-group">
                <label>确认密码:</label>
                <input type="password" class="form-control" placeholder="确认密码" name="pwdconfirm" id="password">
            </div>
            <div class="form-group">
                <label>手机号码:</label>
                <input type="text" class="form-control" placeholder="请输入手机号码:" name="mobile" id="username">
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block">确认注册</button>
    </form>
</div>
<script src="/static/jquery/jquery.js"></script>
<script src="/static/zui/js/zui.min.js"></script>
<script>
    $(function () {

    })
</script>
</body>
</html>